apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test001-2
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  destination:
    namespace: test001
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: cloud-basic-1/group-2
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true