apiVersion: v1
kind: Pod
metadata:
  name: cloud-basic-1-group-1-3
  namespace: test001
  labels:
     name: test001-nginx
spec:
  containers:
    - name: nginx
      image: nginx:1.14.0
      imagePullPolicy: IfNotPresent
      ports:
      - name: http
        containerPort: 80
---
